# Numpy Complete Tutorials

# >> Importing


In [2]:
import numpy as np

# >> Array() from Numpy 

In [2]:
a = np.array([1,2,3,4,5])           # 1D ARRAY 
b = np.array([[1,3],[2,4]])         # 2D ARRAY 
print(a)
print(b)

[1 2 3 4 5]
[[1 3]
 [2 4]]


# >> Arange() from Numpy

In [4]:
a = np.arange(0,12)               # ARRAY WITH START AND END
b = np.arange(1,10,2)             # ARRAY WITH START,END,INTERVAL  
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 3 5 7 9]


# >> Zeros() from Numpy

In [12]:
a = np.zeros(3)                # ARRAY WITH 3 ZEROS 
b = np.zeros((3,3))            # ARRAY WITH COL AND ROW 
c = np.zeros(5,"int")          # ARRAY WITH DataType=int 
print(a)
print(b)
print(c)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0 0]


# >> Ones() from Numpy  

In [15]:
A = np.ones(4)                    # ARRAY WITH 4 ONES 
B = np.ones((2,3),"int")          # ARRAY WITH COL AND ROW, datatype=int
print(A)
print(B)

[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


# >> Linspace() from Numpy

In [23]:
a = np.linspace(1,50,num=15)                     # ARRAY FROM 1 TO 50 INCLUDING 15 ELEMENTS
b = np.linspace(2,80,num=10,retstep=True)        # ARRAY FROM 2 TO 80 WITH SAME INTERVAL
c =  np.linspace(1,50,num=15,endpoint=False)     # ARRAY FROM 1 TO 50 WITHOUT 50 
print(a)
print(b)
print(c)

[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
(array([ 2.        , 10.66666667, 19.33333333, 28.        , 36.66666667,
       45.33333333, 54.        , 62.66666667, 71.33333333, 80.        ]), 8.666666666666666)
[ 1.          4.26666667  7.53333333 10.8        14.06666667 17.33333333
 20.6        23.86666667 27.13333333 30.4        33.66666667 36.93333333
 40.2        43.46666667 46.73333333]


# >> Eye() from Numpy

In [28]:
a = np.eye(4,4)                # ARRAY WITH COL AND ROW WITH 1 IN DIAGONAL 
b = np.eye(3,k=1)              # ARRAY WITH 1 IN UPPER DIAGONAL 
print(a)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# >>  Random() from Numpy 

In [37]:
a = np.random.rand(3)                  # RAND() IN RANDOM MODULE GENERATES RANDOM VALUES
b = np.random.rand(4,3)                # RAND() WITH ROW AND COL GENERATES RANDOM VALUES 
c = np.random.randn(4)                 # RANDN() GENERATES RANDOM VALUES INCLUDING -ve 
d = np.random.randint(6,size=5)        # RANDINT() GENERATES RANDOM VALUES WITHIN LOW VALUE 
print(a)
print(b)
print(c)
print(d)

[0.99509206 0.178808   0.50343607]
[[0.57994741 0.24567349 0.39012327]
 [0.44264597 0.80506067 0.3371286 ]
 [0.72015609 0.75838577 0.79060314]
 [0.02548578 0.30144204 0.23525605]]
[ 0.10441087  0.19601233  0.22873621 -0.56783379]
[4 4 0 2 5]


# >> ndim Attribute of Array 
        

In [40]:
a = np.array([1,2,3,4])                    # 1D ARRAY 
b = np.array([[2,4,6],[1,3,5]])            # 2D ARRAY 
print(a.ndim)
print(b.ndim)

1
2


# >> Shape Attribute of Array 

In [41]:
a = np.array([1,2,3,4])                    # ELEMENTS IN 1D ARRAY 
b = np.array([[2,4,6],[1,3,5]])            # ELEMENTS  2D ARRAY 
print(a.shape)
print(b.shape)

(4,)
(2, 3)


# >> Size Attribute of Array 

In [42]:
a = np.array([1,2,3,4])                    # SIZE IN 1D ARRAY BY MULTIPLY 
b = np.array([[2,4,6],[1,3,5]])            # SIZE IN 2D ARRAY BY MULTIPLY 
print(a.size)
print(b.size)

4
6


# >> DataType Attribute of Array 

In [43]:
a = np.array([1,2,3,4])                    # Dtype IN 1D ARRAY 
b = np.array([[2,4,6],[1,3,5]])            # Dtype IN 2D ARRAY 
print(a.dtype)
print(b.dtype)

int32
int32


# >> Itemsize Attribute of Array 

In [45]:
a = np.array([1,2,3,4])                    # SIZE OF EACH ITEM IN 1D ARRAY 
b = np.array([[2,4,6],[1,3,5]])            # SIZE OF EACH ITEM IN 2D ARRAY 
print(a.itemsize)
print(b.itemsize)

4
4


# >> Indexing on Array

In [26]:
a = np.array([1,2,3,4,5,6,7])               # INDEXING ON 1D ARRAY 
b = np.array([[1,3,5],[2,4,6]])             # INDEXING ON 2D ARRAY 
print(a,a[3])
print(b,b[0][1])


[1 2 3 4 5 6 7] 4
[[1 3 5]
 [2 4 6]] 3


# >> Slicing on Array 

In [41]:
a = np.array([1,2,3,4,5,6,7])               # SLICING ON 1D ARRAY 
b = np.array([[1,3,5],[2,4,6]])             # SLICING ON 2D ARRAY 
print(a,a[3:])
print(b,b[1:,1:])


[1 2 3 4 5 6 7] [4 5 6 7]
[[1 3 5]
 [2 4 6]] [[4 6]]


# >> Advanced Indexing on Array

In [30]:
a = np.array([10,20,30,40,50])
index = np.array([0,1,2])
print(a[index])                              # INTEGER INDEXING ON 1D ARRAY 
b = np.array([[-1,3,5],[2,-4,6]])
print(b[b<0])                                # BOOLEAN INDEXING ON 2D ARRAY 




[10 20 30]
[-1 -4]


# >> Arithmetic Operation on Array 

In [43]:
a = np.arange(0,5)
b = np.array([10,20,30,40,50])
print(a+3)                              # ADD ON 1D ARRAY 
print(a-2)                              # SUB ON 1D ARRAY
print(a*4)                              # MUL ON 1D ARRAY
print(a/2)                              # DIV ON 1D ARRAY     
print(a+b)                              # ADD BOTH ARRAY 1D ARRAY 
print(a-b)                              # SUB BOTH ARRAY 1D ARRAY
print(a*b)                              # MUL BOTH ARRAY 1D ARRAY
print(a/b)                              # DIV BOTH ARRAY 1D ARRAY

[3 4 5 6 7]
[-2 -1  0  1  2]
[ 0  4  8 12 16]
[0.  0.5 1.  1.5 2. ]
[10 21 32 43 54]
[-10 -19 -28 -37 -46]
[  0  20  60 120 200]
[0.         0.05       0.06666667 0.075      0.08      ]


# >> Broadcasting on Array 

In [50]:
a = np.arange(1,4)                              # 1D ARRAY WITH SHAPE(3,)
print(a.shape)
b = np.array([[10,20,30],[40,50,60]])           # 2D ARRAY WITH SHAPE(2, 3)
print(b.shape)
print(a+b)


(3,)
(2, 3)
[[11 22 33]
 [41 52 63]]


# >> Array Manipulation  
###                     reshape() , resize() 

In [58]:
a = np.arange(1,7)                             # 1D ARRAY 
b = np.reshape(a,(2,3))                        # RESHAPE INTO 2D WITH ROW 
c = np.reshape(a,(2,3),order="F")              # RESHAPE INTO 2D WITH COL
print(b)
print(c)
d = np.arange(1,11)                           # 1D ARRAY 
e = np.resize(d,(5,3))                        # RESIZE INTO 2D WITH ROW 
f = np.resize(d,(3,5))                        # RESIZE INTO 2D WITH COL
print(e)
print(f)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  1  2]
 [ 3  4  5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


# >> Array Manipulation 
###      flatten() , ravel() 

In [99]:
a = np.arange(1,4)                                                  # 1D ARRAY 
print(a.flatten())
b = np.array([[10,20,30],[40,50,60]])                               # 2D ARRAY INTO 1D ARRAY USING FLATTEN
print( b.flatten())
c = np.arange(1,11)                                                 # 1D ARRAY 
print(c.ravel())
d = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])          # 2D ARRAY INTO 1D ARRAY USING RAVEL
print( d.ravel())


[1 2 3]
[10 20 30 40 50 60]
[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100 110 120]


# >> Array Manipulation 
###      transpose() , swapaxes() 

In [100]:
a = np.arange(1,11).reshape(2,5)
print(a)
print(a.transpose())                          # TRANSPOSE METHOD
print(a.swapaxes(0,1))                        # SWAPAXES METHOD 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# >> Array Manipulation
###      insert() , append() , delete() 

In [98]:
a = np.arange(1,6)                          # 1D ARRAY 
b = np.array([[1,2],[3,4]])                 # 2D ARRAY 
print(a,np.insert(a,0,8))                   # INSERT METHOD ON 1D ARRAY
print(np.insert(b,1,[[10,12]],axis=1))      # INSERT METHOD ON 2D ARRAY
print(a,np.append(a,8))                     # APPEND METHOD ON 1D ARRAY
print(np.append(b,[[10,12]],axis=0))        # APPEND METHOD ON 2D ARRAY
print(a,np.delete(a,3))                     # DELETE METHOD ON 1D ARRAY
print(b,np.delete(b,0,axis=0))              # DELETE METHOD ON 2D ARRAY


[1 2 3 4 5] [8 1 2 3 4 5]
[[ 1 10  2]
 [ 3 12  4]]
[1 2 3 4 5] [1 2 3 4 5 8]
[[ 1  2]
 [ 3  4]
 [10 12]]
[1 2 3 4 5] [1 2 3 5]
[[1 2]
 [3 4]] [[3 4]]


# >> Matrix in Array 

In [9]:
a = np.array([[1,2],[3,4]])                   # 2D ARRAY 
b = np.array([[10,20],[30,40]])               # 2D ARRAY
c = np.matrix("5 6;7 8")                      # 2D ARRAY USING MATRIX CLASS  
print(a+b)                                    # MATRIX ADDITION
print(a.dot(b))                               # MATRIX MULTIPLICATION
print(c*a)                                    # MATRIX MULTIPLICATION

[[11 22]
 [33 44]]
[[ 70 100]
 [150 220]]
[[23 34]
 [31 46]]


# >> Linear Algebra in Array
##       inverse matrix

In [22]:
a = np.matrix("5 6;7 8")                  # 2D ARRAY USING MATRIX CLASS                 
b = np.array([[10,20],[30,40]])           # 2D ARRAY USING NUMPY ARRAY
ans1 = np.linalg.inv(a)                   # INVERSE OF MATRIX
ans2 = np.linalg.inv(b)                   # INVERSE OF MATRIX 
print(ans1)
print(ans2)

[[-4.   3. ]
 [ 3.5 -2.5]]
[[-0.2   0.1 ]
 [ 0.15 -0.05]]


# >> Linear Algebra in Array 
##      power of matrix 

In [20]:
a = np.matrix("5 6;7 8")                              # 2D MATRIX USING MATRIX CLASS
ans1 = np.linalg.matrix_power(a,2)                    # +VE POWER OF 2D MATRIX   
ans2 = np.linalg.matrix_power(a,0)                    # IDENTITY MATRIX 
ans3 = np.linalg.matrix_power(a,-2)                   # -VE POWER OF 2D MATRIX 
print(ans1)
print(ans2)
print(ans3)

[[ 67  78]
 [ 91 106]]
[[1 0]
 [0 1]]
[[ 26.5  -19.5 ]
 [-22.75  16.75]]


#  >> Linear Algebra in Array 
##       Solve Linear Equation 

In [27]:
a = np.array([[3,1],[1,2]])                          # 2D EQUATIONS IN Ax FORM 
b = np.array([9,8])                                  # VALUE OF EQUATIONS IN B FORM 
c = np.array([[6,2,-5],[3,3,-2],[7,5,-1]])           # 3D EQUATIONS IN Ax FORM
d = np.array([13,13,26])                             # VALUE OF EQUATIONS IN B FORM 
ans1 = np.linalg.solve(a,b)                          # EQUATION SOLVER USING SOLVE CLASS
ans2 = np.linalg.solve(c,d)                          # EQUATION SOLVER USING SOLVE CLASS
print(ans1)
print(ans2)

[2. 3.]
[1.56 3.12 0.52]


# >> Linear Algebra in Array 
##      Determinant of Matrix 

In [30]:
a = np.array([[3,1],[1,2]])                     # 2D MATRIX USING NUMPY ARRAY 
b = np.array([[3,1,2],[1,2,3],[4,1,1]])         # 3D MATRIX USING NUMPY ARRAY
ans1 = np.linalg.det(a)                         # DETERMINANT OF 2D MATRIX 
ans2 = np.linalg.det(b)                         # DETERMINANT OF 3D MATRIX
print(ans1)
print(ans2)

5.000000000000001
-6.0
